### PR TITLE
extensions to handle comp files correctly

### PR DESCRIPTION
**Pull request by cfsnook**
Enable Event-B navigator support for CODA models in comp files
Use Extensions persistence for .comp files

### CODE REVIEW

**Comment by tshoang** [comment]
@cfsnook : Can we use *.cmp (3 characters) instead of *.comp (4 characters)?

**Review by tshoang — CHANGES_REQUESTED** [review]
@cfsnook Can you change the .comp to .cmp?

**Comment by cfsnook** [comment]
I would prefer .comp since .cmp is well used.
Maybe we should standardise on 4 letters

**Comment by cfsnook** [comment]
Yep I have quickly done it.

**Review by tshoang — APPROVED** [review]
Great work after a year. :D

**Pull request merged**
